---
- name: Generate certificates locally
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - certs

- name: Copy certs to loghost
  hosts: loghost-mgmt
  become: true
  vars:
    cert_dir: /etc/rsyslog/certs
  tasks:
    - name: Create cert dir
      file: { path: "{{ cert_dir }}", state: directory }

    - name: Copy certs to server
      copy:
        src: "certs/{{ item }}"
        dest: "{{ cert_dir }}/{{ item }}"
        mode: "{{ '0600' if item.endswith('.key') else '0644' }}"
      loop:
        - rsyslog-ca.crt
        - loghost-rsyslog.crt
        - loghost-rsyslog.key

- name: Copy certs to mailhost
  hosts: mailhost-mgmt
  become: true
  vars:
    cert_dir: /etc/rsyslog/certs
  tasks:
    - name: Create cert dir
      file: { path: "{{ cert_dir }}", state: directory }

    - name: Copy certs to client
      copy:
        src: "certs/{{ item }}"
        dest: "{{ cert_dir }}/{{ item }}"
        mode: "{{ '0600' if item.endswith('.key') else '0644' }}"
      loop:
        - rsyslog-ca.crt
        - mailhost-rsyslog.crt
        - mailhost-rsyslog.key

