- name: Create certs directory
  file:
    path: certs
    state: directory

- name: Generate CA key
  command: openssl genrsa -out certs/ca.key 4096
  args: { creates: certs/ca.key }

- name: Generate CA cert
  command: >
    openssl req -x509 -new -nodes -key certs/ca.key
    -sha256 -days 3650 -subj "/C=US/ST=Example/L=Example/O=Example/CN=MyCA"
    -out certs/ca.crt
  args: { creates: certs/ca.crt }

- name: Generate server key
  command: openssl genrsa -out certs/server.key 2048
  args: { creates: certs/server.key }

- name: Generate server CSR
  command: openssl req -new -key certs/server.key -subj "/CN=relp-server" -out certs/server.csr
  args: { creates: certs/server.csr }

- name: Sign server cert
  command: openssl x509 -req -in certs/server.csr -CA certs/ca.crt -CAkey certs/ca.key -CAcreateserial -out certs/server.crt -days 365 -sha256
  args: { creates: certs/server.crt }

- name: Generate client key
  command: openssl genrsa -out certs/client.key 2048
  args: { creates: certs/client.key }

- name: Generate client CSR
  command: openssl req -new -key certs/client.key -subj "/CN=relp-client" -out certs/client.csr
  args: { creates: certs/client.csr }

- name: Sign client cert
  command: openssl x509 -req -in certs/client.csr -CA certs/ca.crt -CAkey certs/ca.key -CAcreateserial -out certs/client.crt -days 365 -sha256
  args: { creates: certs/client.crt }

