- name: Create certs directory
  file:
    path: certs
    state: directory

- name: Generate CA key
  command: openssl genrsa -out certs/rsyslog-ca.key 4096
  args: { creates: certs/rsyslog-ca.key }

- name: Generate CA cert
  command: >
    openssl req -x509 -new -nodes -key certs/rsyslog-ca.key
    -sha256 -days 3650 -subj "/C=CA/ST=Ontario/L=Example/O=Example/CN=NETS1037"
    -out certs/rsyslog-ca.crt
  args: { creates: certs/rsyslog-ca.crt }

- name: Generate server key
  command: openssl genrsa -out certs/loghost-rsyslog.key 2048
  args: { creates: loghost-rsyslog/server.key }

- name: Generate server CSR
  command: openssl req -new -key certs/loghost-rsyslog.key -subj "/CN=loghost-mgmt" -out certs/loghost-rsyslog.csr
  args: { creates: certs/loghost-rsyslog.csr }

- name: Sign server cert
  command: openssl x509 -req -in certs/loghost-rsyslog.csr -CA certs/rsyslog-ca.crt -CAkey certs/rsyslog-ca.key -CAcreateserial -out certs/loghost-rsyslog.crt -days 365 -sha256
  args: { creates: certs/loghost-rsyslog.crt }

- name: Generate mailhost key
  command: openssl genrsa -out certs/mailhost-rsyslog.key 2048
  args: { creates: certs/mailhost-rsyslog.key }

- name: Generate client CSR
  command: openssl req -new -key certs/mailhost-rsyslog.key -subj "/CN=mailhost-mgmt" -out certs/mailhost-rsyslog.csr
  args: { creates: certs/mailhost-rsyslog.csr }

- name: Sign client cert
  command: openssl x509 -req -in certs/mailhost-rsyslog.csr -CA certs/rsyslog-ca.crt -CAkey certs/rsyslog-ca.key -CAcreateserial -out certs/mailhost-rsyslog.crt -days 365 -sha256
  args: { creates: certs/mailhost-rsyslog.crt }

