- name: Install web server and PHP packages
  apt:
    name:
      - apache2
      - php
      - php-mysql
      - php-gd
      - php-pear
      - php-db
      - git
    state: present

- name: Clone Daloradius
  git:
    repo: https://github.com/lirantal/daloradius.git
    dest: /var/www/html/daloradius

#- name: Import daloradius SQL schema part 1
#  command: mysql -u root "{{ db_name }}" < /var/www/html/daloradius/contrib/db/fr3-mariadb-freeradius.sql

#- name: Import daloradius SQL schema part 2
#  command: mysql -u root "{{ db_name }}" < /var/www/html/daloradius/contrib/db/mariadb-daloradius.sql

#- name: create radius database
#  mysql_db:
#    name: "{{ db_name }}"
#    state: present
#    login_unix_socket: /run/mysqld/mysqld.sock

- name: create tables ignoring errors
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    state: import
    target: /var/www/html/daloradius/contrib/db/fr3-mariadb-freeradius.sql
    login_unix_socket: /run/mysqld/mysqld.sock
    force: true

- name: restore starting database content ignoring errors
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    state: import
    target: /var/www/html/daloradius/contrib/db/mariadb-daloradius.sql
    login_unix_socket: /run/mysqld/mysqld.sock
    force: true

- name: Configure Apache for Daloradius
  copy:
    dest: /etc/apache2/sites-available/000-default.conf
    content: |
      <VirtualHost *:80>
        DocumentRoot /var/www/html/daloradius
        <Directory /var/www/html/daloradius>
          Options Indexes FollowSymLinks
          AllowOverride All
          Require all granted
        </Directory>
      </VirtualHost>

- name: Enable Apache rewrite module
  command: a2enmod rewrite

- name: Restart Apache
  service:
    name: apache2
    state: restarted
    enabled: true
